---
title: "Basic Notebook Template"
author:
  name: "Bruce Hartman"
  affiliation: "University of St. Francis"
date: "`r lubridate::today()`"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    theme: united
abstract: |
  This is a good notebook template to start with. 
---

# Introduction {-}
Here write what you are going to do. Add a reference [(Hartman, 2004)](#r1).

# Packages {-}
The `devtools` package will be installed, if you have not already done so, and loaded. Then we install and load package `mbadtools` from GitHub. This package is used in USF's MBAD courses and is not on CRAN. The `mbad_standard_packages` object contains a list of required packages for this course that you will need to install first.   
```{r}
# allow package installation from github
if(!("devtools" %in% installed.packages())) install.packages("devtools")
library(devtools) # Make sure that the devtools library is loaded
# install mbadtools from github
if(!("mbadtools" %in% installed.packages())) devtools::install_github("bhartman2/mbadtools")
# load github packages
library(mbadtools)
# list of packages to install
data("mbad_standard_packages")
mbad_standard_packages
# load packages to the notebook
lib_packages(mbad_standard_packages, quiet=TRUE)
```

# Data {-}
Here we get the data using Import Dataset or from a package.

# Data Description {-}
Describe the data using simple display, or `skim`.

# Research Problem {-}
You might want to state the problem you will solve.

# Data Wrangling {-}
Make changes to the data for analysis.

# Data Visualization
Graphic displays of data such as pairs plot

# Analysis {-}
Explain what analysis you are doing. Add a formula in math notation like this:
::: {#eq1}
$$E = mc^2\hspace{100pt} (1)$$
:::

## Analysis Section {-}
An extension of the analysis. Notice two ## and space for header 2.
> Blockquote some text from the text or an article

# Conclusion {-}
My conclusions are ...  Refer back to a formula or location in this document: [Equation 1](#eq1)

# References {-}
::: {#r1}
1. Hartman, B. (2024) Basic Notebook Template. (https://github.com/bhartman2/mbadtools/blob/main/notebook/Basic%20Notebook%20Template.Rmd)
:::

